var map = {
" background": 0,
"tench": 0,
"goldfish": 0,
"great white shark": 0,
"tiger shark": 0,
"hammerhead": 0,
"electric ray": 0,
"stingray": 0,
"cock": 0,
"hen": 0,
"ostrich": 0,
"brambling": 0,
"goldfinch": 0,
"house finch": 0,
"junco": 0,
"indigo bunting": 0,
"robin": 0,
"bulbul": 0,
"jay": 0,
"magpie": 0,
"chickadee": 0,
"water ouzel": 0,
"kite": 0,
"bald eagle": 0,
"vulture": 0,
"great grey owl": 0,
"European fire salamander": 0,
"common newt": 0,
"eft": 0,
"spotted salamander": 0,
"axolotl": 0,
"bullfrog": 0,
"tree frog": 0,
"tailed frog": 0,
"loggerhead": 0,
"leatherback turtle": 0,
"mud turtle": 0,
"terrapin": 0,
"box turtle": 0,
"banded gecko": 0,
"common iguana": 0,
"American chameleon": 0,
"whiptail": 0,
"agama": 0,
"frilled lizard": 0,
"alligator lizard": 0,
"Gila monster": 0,
"green lizard": 0,
"African chameleon": 0,
"Komodo dragon": 0,
"African crocodile": 0,
"American alligator": 0,
"triceratops": 0,
"thunder snake": 0,
"ringneck snake": 0,
"hognose snake": 0,
"green snake": 0,
"king snake": 0,
"garter snake": 0,
"water snake": 0,
"vine snake": 0,
"night snake": 0,
"boa constrictor": 0,
"rock python": 0,
"Indian cobra": 0,
"green mamba": 0,
"sea snake": 0,
"horned viper": 0,
"diamondback": 0,
"sidewinder": 0,
"trilobite": 0,
"harvestman": 0,
"scorpion": 0,
"black and gold garden spider": 0,
"barn spider": 0,
"garden spider": 0,
"black widow": 0,
"tarantula": 0,
"wolf spider": 0,
"tick": 0,
"centipede": 0,
"black grouse": 0,
"ptarmigan": 0,
"ruffed grouse": 0,
"prairie chicken": 0,
"peacock": 0,
"quail": 0,
"partridge": 0,
"African grey": 0,
"macaw": 0,
"sulphur-crested cockatoo": 0,
"lorikeet": 0,
"coucal": 0,
"bee eater": 0,
"hornbill": 0,
"hummingbird": 0,
"jacamar": 0,
"toucan": 0,
"drake": 0,
"red-breasted merganser": 0,
"goose": 0,
"black swan": 0,
"tusker": 0,
"echidna": 0,
"platypus": 0,
"wallaby": 0,
"koala": 0,
"wombat": 0,
"jellyfish": 0,
"sea anemone": 0,
"brain coral": 0,
"flatworm": 0,
"nematode": 0,
"conch": 0,
"snail": 0,
"slug": 0,
"sea slug": 0,
"chiton": 0,
"chambered nautilus": 0,
"Dungeness crab": 0,
"rock crab": 0,
"fiddler crab": 0,
"king crab": 0,
"American lobster": 0,
"spiny lobster": 0,
"crayfish": 0,
"hermit crab": 0,
"isopod": 0,
"white stork": 0,
"black stork": 0,
"spoonbill": 0,
"flamingo": 0,
"little blue heron": 0,
"American egret": 0,
"bittern": 0,
"crane": 0,
"limpkin": 0,
"European gallinule": 0,
"American coot": 0,
"bustard": 0,
"ruddy turnstone": 0,
"red-backed sandpiper": 0,
"redshank": 0,
"dowitcher": 0,
"oystercatcher": 0,
"pelican": 0,
"king penguin": 0,
"albatross": 0,
"grey whale": 0,
"killer whale": 0,
"dugong": 0,
"sea lion": 0,
"Chihuahua": 0,
"Japanese spaniel": 0,
"Maltese dog": 0,
"Pekinese": 0,
"Shih-Tzu": 0,
"Blenheim spaniel": 0,
"papillon": 0,
"toy terrier": 0,
"Rhodesian ridgeback": 0,
"Afghan hound": 0,
"basset": 0,
"beagle": 0,
"bloodhound": 0,
"bluetick": 0,
"black-and-tan coonhound": 0,
"Walker hound": 0,
"English foxhound": 0,
"redbone": 0,
"borzoi": 0,
"Irish wolfhound": 0,
"Italian greyhound": 0,
"whippet": 0,
"Ibizan hound": 0,
"Norwegian elkhound": 0,
"otterhound": 0,
"Saluki": 0,
"Scottish deerhound": 0,
"Weimaraner": 0,
"Staffordshire bullterrier": 0,
"American Staffordshire terrier": 0,
"Bedlington terrier": 0,
"Border terrier": 0,
"Kerry blue terrier": 0,
"Irish terrier": 0,
"Norfolk terrier": 0,
"Norwich terrier": 0,
"Yorkshire terrier": 0,
"wire-haired fox terrier": 0,
"Lakeland terrier": 0,
"Sealyham terrier": 0,
"Airedale": 0,
"cairn": 0,
"Australian terrier": 0,
"Dandie Dinmont": 0,
"Boston bull": 0,
"miniature schnauzer": 0,
"giant schnauzer": 0,
"standard schnauzer": 0,
"Scotch terrier": 0,
"Tibetan terrier": 0,
"silky terrier": 0,
"soft-coated wheaten terrier": 0,
"West Highland white terrier": 0,
"Lhasa": 0,
"flat-coated retriever": 0,
"curly-coated retriever": 0,
"golden retriever": 0,
"Labrador retriever": 0,
"Chesapeake Bay retriever": 0,
"German short-haired pointer": 0,
"vizsla": 0,
"English setter": 0,
"Irish setter": 0,
"Gordon setter": 0,
"Brittany spaniel": 0,
"clumber": 0,
"English springer": 0,
"Welsh springer spaniel": 0,
"cocker spaniel": 0,
"Sussex spaniel": 0,
"Irish water spaniel": 0,
"kuvasz": 0,
"schipperke": 0,
"groenendael": 0,
"malinois": 0,
"briard": 0,
"kelpie": 0,
"komondor": 0,
"Old English sheepdog": 0,
"Shetland sheepdog": 0,
"collie": 0,
"Border collie": 0,
"Bouvier des Flandres": 0,
"Rottweiler": 0,
"German shepherd": 0,
"Doberman": 0,
"miniature pinscher": 0,
"Greater Swiss Mountain dog": 0,
"Bernese mountain dog": 0,
"Appenzeller": 0,
"EntleBucher": 0,
"boxer": 0,
"bull mastiff": 0,
"Tibetan mastiff": 0,
"French bulldog": 0,
"Great Dane": 0,
"Saint Bernard": 0,
"Eskimo dog": 0,
"malamute": 0,
"Siberian husky": 0,
"dalmatian": 0,
"affenpinscher": 0,
"basenji": 0,
"pug": 0,
"Leonberg": 0,
"Newfoundland": 0,
"Great Pyrenees": 0,
"Samoyed": 0,
"Pomeranian": 0,
"chow": 0,
"keeshond": 0,
"Brabancon griffon": 0,
"Pembroke": 0,
"Cardigan": 0,
"toy poodle": 0,
"miniature poodle": 0,
"standard poodle": 0,
"Mexican hairless": 0,
"timber wolf": 0,
"white wolf": 0,
"red wolf": 0,
"coyote": 0,
"dingo": 0,
"dhole": 0,
"African hunting dog": 0,
"hyena": 0,
"red fox": 0,
"kit fox": 0,
"Arctic fox": 0,
"grey fox": 0,
"tabby": 0,
"tiger cat": 0,
"Persian cat": 0,
"Siamese cat": 0,
"Egyptian cat": 0,
"cougar": 0,
"lynx": 0,
"leopard": 0,
"snow leopard": 0,
"jaguar": 0,
"lion": 0,
"tiger": 0,
"cheetah": 0,
"brown bear": 0,
"American black bear": 0,
"ice bear": 0,
"sloth bear": 0,
"mongoose": 0,
"meerkat": 0,
"tiger beetle": 0,
"ladybug": 0,
"ground beetle": 0,
"long-horned beetle": 0,
"leaf beetle": 0,
"dung beetle": 0,
"rhinoceros beetle": 0,
"weevil": 0,
"fly": 0,
"bee": 0,
"ant": 0,
"grasshopper": 0,
"cricket": 0,
"walking stick": 0,
"cockroach": 0,
"mantis": 0,
"cicada": 0,
"leafhopper": 0,
"lacewing": 0,
"dragonfly": 0,
"damselfly": 0,
"admiral": 0,
"ringlet": 0,
"monarch": 0,
"cabbage butterfly": 0,
"sulphur butterfly": 0,
"lycaenid": 0,
"starfish": 0,
"sea urchin": 0,
"sea cucumber": 0,
"wood rabbit": 0,
"hare": 0,
"Angora": 0,
"hamster": 0,
"porcupine": 0,
"fox squirrel": 0,
"marmot": 0,
"beaver": 0,
"guinea pig": 0,
"sorrel": 0,
"zebra": 0,
"hog": 0,
"wild boar": 0,
"warthog": 0,
"hippopotamus": 0,
"ox": 0,
"water buffalo": 0,
"bison": 0,
"ram": 0,
"bighorn": 0,
"ibex": 0,
"hartebeest": 0,
"impala": 0,
"gazelle": 0,
"Arabian camel": 0,
"llama": 0,
"weasel": 0,
"mink": 0,
"polecat": 0,
"black-footed ferret": 0,
"otter": 0,
"skunk": 0,
"badger": 0,
"armadillo": 0,
"three-toed sloth": 0,
"orangutan": 0,
"gorilla": 0,
"chimpanzee": 0,
"gibbon": 0,
"siamang": 0,
"guenon": 0,
"patas": 0,
"baboon": 0,
"macaque": 0,
"langur": 0,
"colobus": 0,
"proboscis monkey": 0,
"marmoset": 0,
"capuchin": 0,
"howler monkey": 0,
"titi": 0,
"spider monkey": 0,
"squirrel monkey": 0,
"Madagascar cat": 0,
"indri": 0,
"Indian elephant": 0,
"African elephant": 0,
"lesser panda": 0,
"giant panda": 0,
"barracouta": 0,
"eel": 0,
"coho": 0,
"rock beauty": 0,
"anemone fish": 0,
"sturgeon": 0,
"gar": 0,
"lionfish": 0,
"puffer": 0,
"abacus": 0,
"abaya": 0,
"academic gown": 0,
"accordion": 0,
"acoustic guitar": 0,
"aircraft carrier": 0,
"airliner": 0,
"airship": 0,
"altar": 0,
"ambulance": 0,
"amphibian": 0,
"analog clock": 0,
"apiary": 0,
"apron": 0,
"ashcan": 0,
"assault rifle": 0,
"backpack": 0,
"bakery": 0,
"balance beam": 0,
"balloon": 0,
"ballpoint": 0,
"Band Aid": 0,
"banjo": 0,
"bannister": 0,
"barbell": 0,
"barber chair": 0,
"barbershop": 0,
"barn": 0,
"barometer": 0,
"barrel": 0,
"barrow": 0,
"baseball": 0,
"basketball": 0,
"bassinet": 0,
"bassoon": 0,
"bathing cap": 0,
"bath towel": 0,
"bathtub": 0,
"beach wagon": 0,
"beacon": 0,
"beaker": 0,
"bearskin": 0,
"beer bottle": 0,
"beer glass": 0,
"bell cote": 0,
"bib": 0,
"bicycle-built-for-two": 0,
"bikini": 0,
"binder": 0,
"binoculars": 0,
"birdhouse": 0,
"boathouse": 0,
"bobsled": 0,
"bolo tie": 0,
"bonnet": 0,
"bookcase": 0,
"bookshop": 0,
"bottlecap": 0,
"bow": 0,
"bow tie": 0,
"brass": 0,
"brassiere": 0,
"breakwater": 0,
"breastplate": 0,
"broom": 0,
"bucket": 0,
"buckle": 0,
"bulletproof vest": 0,
"bullet train": 0,
"butcher shop": 0,
"cab": 0,
"caldron": 0,
"candle": 0,
"cannon": 0,
"canoe": 0,
"can opener": 0,
"cardigan": 0,
"car mirror": 0,
"carousel": 0,
"carpenter's kit": 0,
"carton": 0,
"car wheel": 0,
"cash machine": 0,
"cassette": 0,
"cassette player": 0,
"castle": 0,
"catamaran": 0,
"CD player": 0,
"cello": 0,
"cellular telephone": 0,
"chain": 0,
"chainlink fence": 0,
"chain mail": 0,
"chain saw": 0,
"chest": 0,
"chiffonier": 0,
"chime": 0,
"china cabinet": 0,
"Christmas stocking": 0,
"church": 0,
"cinema": 0,
"cleaver": 0,
"cliff dwelling": 0,
"cloak": 0,
"clog": 0,
"cocktail shaker": 0,
"coffee mug": 0,
"coffeepot": 0,
"coil": 0,
"combination lock": 0,
"computer keyboard": 0,
"confectionery": 0,
"container ship": 0,
"convertible": 0,
"corkscrew": 0,
"cornet": 0,
"cowboy boot": 0,
"cowboy hat": 0,
"cradle": 0,
"crane": 0,
"crash helmet": 0,
"crate": 0,
"crib": 0,
"Crock Pot": 0,
"croquet ball": 0,
"crutch": 0,
"cuirass": 0,
"dam": 0,
"desk": 0,
"desktop computer": 0,
"dial telephone": 0,
"diaper": 0,
"digital clock": 0,
"digital watch": 0,
"dining table": 0,
"dishrag": 0,
"dishwasher": 0,
"disk brake": 0,
"dock": 0,
"dogsled": 0,
"dome": 0,
"doormat": 0,
"drilling platform": 0,
"drum": 0,
"drumstick": 0,
"dumbbell": 0,
"Dutch oven": 0,
"electric fan": 0,
"electric guitar": 0,
"electric locomotive": 0,
"entertainment center": 0,
"envelope": 0,
"espresso maker": 0,
"face powder": 0,
"feather boa": 0,
"file": 0,
"fireboat": 0,
"fire engine": 0,
"fire screen": 0,
"flagpole": 0,
"flute": 0,
"folding chair": 0,
"football helmet": 0,
"forklift": 0,
"fountain": 0,
"fountain pen": 0,
"four-poster": 0,
"freight car": 0,
"French horn": 0,
"frying pan": 0,
"fur coat": 0,
"garbage truck": 0,
"gasmask": 0,
"gas pump": 0,
"goblet": 0,
"go-kart": 0,
"golf ball": 0,
"golfcart": 0,
"gondola": 0,
"gong": 0,
"gown": 0,
"grand piano": 0,
"greenhouse": 0,
"grille": 0,
"grocery store": 0,
"guillotine": 0,
"hair slide": 0,
"hair spray": 0,
"half track": 0,
"hammer": 0,
"hamper": 0,
"hand blower": 0,
"hand-held computer": 0,
"handkerchief": 0,
"hard disc": 0,
"harmonica": 0,
"harp": 0,
"harvester": 0,
"hatchet": 0,
"holster": 0,
"home theater": 0,
"honeycomb": 0,
"hook": 0,
"hoopskirt": 0,
"horizontal bar": 0,
"horse cart": 0,
"hourglass": 0,
"iPod": 0,
"iron": 0,
"jack-o'-lantern": 0,
"jean": 0,
"jeep": 0,
"jersey": 0,
"jigsaw puzzle": 0,
"jinrikisha": 0,
"joystick": 0,
"kimono": 0,
"knee pad": 0,
"knot": 0,
"lab coat": 0,
"ladle": 0,
"lampshade": 0,
"laptop": 0,
"lawn mower": 0,
"lens cap": 0,
"letter opener": 0,
"library": 0,
"lifeboat": 0,
"lighter": 0,
"limousine": 0,
"liner": 0,
"lipstick": 0,
"Loafer": 0,
"lotion": 0,
"loudspeaker": 0,
"loupe": 0,
"lumbermill": 0,
"magnetic compass": 0,
"mailbag": 0,
"mailbox": 0,
"maillot": 0,
"maillot": 0,
"manhole cover": 0,
"maraca": 0,
"marimba": 0,
"mask": 0,
"matchstick": 0,
"maypole": 0,
"maze": 0,
"measuring cup": 0,
"medicine chest": 0,
"megalith": 0,
"microphone": 0,
"microwave": 0,
"military uniform": 0,
"milk can": 0,
"minibus": 0,
"miniskirt": 0,
"minivan": 0,
"missile": 0,
"mitten": 0,
"mixing bowl": 0,
"mobile home": 0,
"Model T": 0,
"modem": 0,
"monastery": 0,
"monitor": 0,
"moped": 0,
"mortar": 0,
"mortarboard": 0,
"mosque": 0,
"mosquito net": 0,
"motor scooter": 0,
"mountain bike": 0,
"mountain tent": 0,
"mouse": 0,
"mousetrap": 0,
"moving van": 0,
"muzzle": 0,
"nail": 0,
"neck brace": 0,
"necklace": 0,
"nipple": 0,
"notebook": 0,
"obelisk": 0,
"oboe": 0,
"ocarina": 0,
"odometer": 0,
"oil filter": 0,
"organ": 0,
"oscilloscope": 0,
"overskirt": 0,
"oxcart": 0,
"oxygen mask": 0,
"packet": 0,
"paddle": 0,
"paddlewheel": 0,
"padlock": 0,
"paintbrush": 0,
"pajama": 0,
"palace": 0,
"panpipe": 0,
"paper towel": 0,
"parachute": 0,
"parallel bars": 0,
"park bench": 0,
"parking meter": 0,
"passenger car": 0,
"patio": 0,
"pay-phone": 0,
"pedestal": 0,
"pencil box": 0,
"pencil sharpener": 0,
"perfume": 0,
"Petri dish": 0,
"photocopier": 0,
"pick": 0,
"pickelhaube": 0,
"picket fence": 0,
"pickup": 0,
"pier": 0,
"piggy bank": 0,
"pill bottle": 0,
"pillow": 0,
"ping-pong ball": 0,
"pinwheel": 0,
"pirate": 0,
"pitcher": 0,
"plane": 0,
"planetarium": 0,
"plastic bag": 0,
"plate rack": 0,
"plow": 0,
"plunger": 0,
"Polaroid camera": 0,
"pole": 0,
"police van": 0,
"poncho": 0,
"pool table": 0,
"pop bottle": 0,
"pot": 0,
"potter's wheel": 0,
"power drill": 0,
"prayer rug": 0,
"printer": 0,
"prison": 0,
"projectile": 0,
"projector": 0,
"puck": 0,
"punching bag": 0,
"purse": 0,
"quill": 0,
"quilt": 0,
"racer": 0,
"racket": 0,
"radiator": 0,
"radio": 0,
"radio telescope": 0,
"rain barrel": 0,
"recreational vehicle": 0,
"reel": 0,
"reflex camera": 0,
"refrigerator": 0,
"remote control": 0,
"restaurant": 0,
"revolver": 0,
"rifle": 0,
"rocking chair": 0,
"rotisserie": 0,
"rubber eraser": 0,
"rugby ball": 0,
"rule": 0,
"running shoe": 0,
"safe": 0,
"safety pin": 0,
"saltshaker": 0,
"sandal": 0,
"sarong": 0,
"sax": 0,
"scabbard": 0,
"scale": 0,
"school bus": 0,
"schooner": 0,
"scoreboard": 0,
"screen": 0,
"screw": 0,
"screwdriver": 0,
"seat belt": 0,
"sewing machine": 0,
"shield": 0,
"shoe shop": 0,
"shoji": 0,
"shopping basket": 0,
"shopping cart": 0,
"shovel": 0,
"shower cap": 0,
"shower curtain": 0,
"ski": 0,
"ski mask": 0,
"sleeping bag": 0,
"slide rule": 0,
"sliding door": 0,
"slot": 0,
"snorkel": 0,
"snowmobile": 0,
"snowplow": 0,
"soap dispenser": 0,
"soccer ball": 0,
"sock": 0,
"solar dish": 0,
"sombrero": 0,
"soup bowl": 0,
"space bar": 0,
"space heater": 0,
"space shuttle": 0,
"spatula": 0,
"speedboat": 0,
"spider web": 0,
"spindle": 0,
"sports car": 0,
"spotlight": 0,
"stage": 0,
"steam locomotive": 0,
"steel arch bridge": 0,
"steel drum": 0,
"stethoscope": 0,
"stole": 0,
"stone wall": 0,
"stopwatch": 0,
"stove": 0,
"strainer": 0,
"streetcar": 0,
"stretcher": 0,
"studio couch": 0,
"stupa": 0,
"submarine": 0,
"suit": 0,
"sundial": 0,
"sunglass": 0,
"sunglasses": 0,
"sunscreen": 0,
"suspension bridge": 0,
"swab": 0,
"sweatshirt": 0,
"swimming trunks": 0,
"swing": 0,
"switch": 0,
"syringe": 0,
"table lamp": 0,
"tank": 0,
"tape player": 0,
"teapot": 0,
"teddy": 0,
"television": 0,
"tennis ball": 0,
"thatch": 0,
"theater curtain": 0,
"thimble": 0,
"thresher": 0,
"throne": 0,
"tile roof": 0,
"toaster": 0,
"tobacco shop": 0,
"toilet seat": 0,
"torch": 0,
"totem pole": 0,
"tow truck": 0,
"toyshop": 0,
"tractor": 0,
"trailer truck": 0,
"tray": 0,
"trench coat": 0,
"tricycle": 0,
"trimaran": 0,
"tripod": 0,
"triumphal arch": 0,
"trolleybus": 0,
"trombone": 0,
"tub": 0,
"turnstile": 0,
"typewriter keyboard": 0,
"umbrella": 0,
"unicycle": 0,
"upright": 0,
"vacuum": 0,
"vase": 0,
"vault": 0,
"velvet": 0,
"vending machine": 0,
"vestment": 0,
"viaduct": 0,
"violin": 0,
"volleyball": 0,
"waffle iron": 0,
"wall clock": 0,
"wallet": 0,
"wardrobe": 0,
"warplane": 0,
"washbasin": 0,
"washer": 0,
"water bottle": 0,
"water jug": 0,
"water tower": 0,
"whiskey jug": 0,
"whistle": 0,
"wig": 0,
"window screen": 0,
"window shade": 0,
"Windsor tie": 0,
"wine bottle": 0,
"wing": 0,
"wok": 0,
"wooden spoon": 0,
"wool": 0,
"worm fence": 0,
"wreck": 0,
"yawl": 0,
"yurt": 0,
"web site": 0,
"comic book": 0,
"crossword puzzle": 0,
"street sign": 0,
"traffic light": 0,
"book jacket": 0,
"menu": 0,
"plate": 0,
"guacamole": 0,
"consomme": 0,
"hot pot": 0,
"trifle": 0,
"ice cream": 0,
"ice lolly": 0,
"French loaf": 0,
"bagel": 0,
"pretzel": 0,
"cheeseburger": 0,
"hotdog": 0,
"mashed potato": 0,
"head cabbage": 0,
"broccoli": 0,
"cauliflower": 0,
"zucchini": 0,
"spaghetti squash": 0,
"acorn squash": 0,
"butternut squash": 0,
"cucumber": 0,
"artichoke": 0,
"bell pepper": 0,
"cardoon": 0,
"mushroom": 0,
"Granny Smith": 0,
"strawberry": 0,
"orange": 0,
"lemon": 0,
"fig": 0,
"pineapple": 0,
"banana": 0,
"jackfruit": 0,
"custard apple": 0,
"pomegranate": 0,
"hay": 0,
"carbonara": 0,
"chocolate sauce": 0,
"dough": 0,
"meat loaf": 0,
"pizza": 0,
"potpie": 0,
"burrito": 0,
"red wine": 0,
"espresso": 0,
"cup": 0,
"eggnog": 0,
"alp": 0,
"bubble": 0,
"cliff": 0,
"coral reef": 0,
"geyser": 0,
"lakeside": 0,
"promontory": 0,
"sandbar": 0,
"seashore": 0,
"valley": 0,
"volcano": 0,
"ballplayer": 0,
"groom": 0,
"scuba diver": 0,
"rapeseed": 0,
"daisy": 0,
"yellow lady's slipper": 0,
"corn": 0,
"acorn": 0,
"hip": 0,
"buckeye": 0,
"coral fungus": 0,
"agaric": 0,
"gyromitra": 0,
"stinkhorn": 0,
"earthstar": 0,
"hen-of-the-woods": 0,
"bolete": 0,
"ear": 0,
"toilet tissue": 0,
};