var map = {
  " background": 9,
  "tench": 6,
  "goldfish": 6,
  "great white shark": 6,
  "tiger shark": 6,
  "hammerhead": 6,
  "electric ray": 6,
  "stingray": 6,
  "cock": 6,
  "hen": 6,
  "ostrich": 6,
  "brambling": 6,
  "goldfinch": 6,
  "house finch": 6,
  "junco": 6,
  "indigo bunting": 6,
  "robin": 6,
  "bulbul": 6,
  "jay": 6,
  "magpie": 6,
  "chickadee": 6,
  "water ouzel": 6,
  "kite": 6,
  "bald eagle": 6,
  "vulture": 6,
  "great grey owl": 6,
  "European fire salamander": 6,
  "common newt": 6,
  "eft": 6,
  "spotted salamander": 6,
  "axolotl": 6,
  "bullfrog": 6,
  "tree frog": 6,
  "tailed frog": 6,
  "loggerhead": 6,
  "leatherback turtle": 6,
  "mud turtle": 6,
  "terrapin": 6,
  "box turtle": 6,
  "banded gecko": 6,
  "common iguana": 6,
  "American chameleon": 6,
  "whiptail": 6,
  "agama": 6,
  "frilled lizard": 6,
  "alligator lizard": 6,
  "Gila monster": 6,
  "green lizard": 6,
  "African chameleon": 6,
  "Komodo dragon": 6,
  "African crocodile": 6,
  "American alligator": 6,
  "triceratops": 6,
  "thunder snake": 6,
  "ringneck snake": 6,
  "hognose snake": 6,
  "green snake": 6,
  "king snake": 6,
  "garter snake": 6,
  "water snake": 6,
  "vine snake": 6,
  "night snake": 6,
  "boa constrictor": 6,
  "rock python": 6,
  "Indian cobra": 6,
  "green mamba": 6,
  "sea snake": 6,
  "horned viper": 6,
  "diamondback": 6,
  "sidewinder": 6,
  "trilobite": 6,
  "harvestman": 6,
  "scorpion": 6,
  "black and gold garden spider": 6,
  "barn spider": 6,
  "garden spider": 6,
  "black widow": 6,
  "tarantula": 6,
  "wolf spider": 6,
  "tick": 6,
  "centipede": 6,
  "black grouse": 6,
  "ptarmigan": 6,
  "ruffed grouse": 6,
  "prairie chicken": 6,
  "peacock": 6,
  "quail": 6,
  "partridge": 6,
  "African grey": 6,
  "macaw": 6,
  "sulphur-crested cockatoo": 6,
  "lorikeet": 6,
  "coucal": 6,
  "bee eater": 6,
  "hornbill": 6,
  "hummingbird": 6,
  "jacamar": 6,
  "toucan": 6,
  "drake": 6,
  "red-breasted merganser": 6,
  "goose": 6,
  "black swan": 6,
  "tusker": 6,
  "echidna": 6,
  "platypus": 6,
  "wallaby": 6,
  "koala": 6,
  "wombat": 6,
  "jellyfish": 6,
  "sea anemone": 6,
  "brain coral": 6,
  "flatworm": 6,
  "nematode": 6,
  "conch": 6,
  "snail": 6,
  "slug": 6,
  "sea slug": 6,
  "chiton": 6,
  "chambered nautilus": 6,
  "Dungeness crab": 6,
  "rock crab": 6,
  "fiddler crab": 6,
  "king crab": 6,
  "American lobster": 6,
  "spiny lobster": 6,
  "crayfish": 6,
  "hermit crab": 6,
  "isopod": 6,
  "white stork": 6,
  "black stork": 6,
  "spoonbill": 6,
  "flamingo": 6,
  "little blue heron": 6,
  "American egret": 6,
  "bittern": 6,
  "crane": 6,
  "limpkin": 6,
  "European gallinule": 6,
  "American coot": 6,
  "bustard": 6,
  "ruddy turnstone": 6,
  "red-backed sandpiper": 6,
  "redshank": 6,
  "dowitcher": 6,
  "oystercatcher": 6,
  "pelican": 6,
  "king penguin": 6,
  "albatross": 6,
  "grey whale": 6,
  "killer whale": 6,
  "dugong": 6,
  "sea lion": 6,
  "Chihuahua": 6,
  "Japanese spaniel": 6,
  "Maltese dog": 6,
  "Pekinese": 6,
  "Shih-Tzu": 6,
  "Blenheim spaniel": 6,
  "papillon": 6,
  "toy terrier": 6,
  "Rhodesian ridgeback": 6,
  "Afghan hound": 6,
  "basset": 6,
  "beagle": 6,
  "bloodhound": 6,
  "bluetick": 6,
  "black-and-tan coonhound": 6,
  "Walker hound": 6,
  "English foxhound": 6,
  "redbone": 6,
  "borzoi": 6,
  "Irish wolfhound": 6,
  "Italian greyhound": 6,
  "whippet": 6,
  "Ibizan hound": 6,
  "Norwegian elkhound": 6,
  "otterhound": 6,
  "Saluki": 6,
  "Scottish deerhound": 6,
  "Weimaraner": 6,
  "Staffordshire bullterrier": 6,
  "American Staffordshire terrier": 6,
  "Bedlington terrier": 6,
  "Border terrier": 6,
  "Kerry blue terrier": 6,
  "Irish terrier": 6,
  "Norfolk terrier": 6,
  "Norwich terrier": 6,
  "Yorkshire terrier": 6,
  "wire-haired fox terrier": 6,
  "Lakeland terrier": 6,
  "Sealyham terrier": 6,
  "Airedale": 6,
  "cairn": 6,
  "Australian terrier": 6,
  "Dandie Dinmont": 6,
  "Boston bull": 6,
  "miniature schnauzer": 6,
  "giant schnauzer": 6,
  "standard schnauzer": 6,
  "Scotch terrier": 6,
  "Tibetan terrier": 6,
  "silky terrier": 6,
  "soft-coated wheaten terrier": 6,
  "West Highland white terrier": 6,
  "Lhasa": 6,
  "flat-coated retriever": 6,
  "curly-coated retriever": 6,
  "golden retriever": 6,
  "Labrador retriever": 6,
  "Chesapeake Bay retriever": 6,
  "German short-haired pointer": 6,
  "vizsla": 6,
  "English setter": 6,
  "Irish setter": 6,
  "Gordon setter": 6,
  "Brittany spaniel": 6,
  "clumber": 6,
  "English springer": 6,
  "Welsh springer spaniel": 6,
  "cocker spaniel": 6,
  "Sussex spaniel": 6,
  "Irish water spaniel": 6,
  "kuvasz": 6,
  "schipperke": 6,
  "groenendael": 6,
  "malinois": 6,
  "briard": 6,
  "kelpie": 6,
  "komondor": 6,
  "Old English sheepdog": 6,
  "Shetland sheepdog": 6,
  "collie": 6,
  "Border collie": 6,
  "Bouvier des Flandres": 6,
  "Rottweiler": 6,
  "German shepherd": 6,
  "Doberman": 6,
  "miniature pinscher": 6,
  "Greater Swiss Mountain dog": 6,
  "Bernese mountain dog": 6,
  "Appenzeller": 6,
  "EntleBucher": 6,
  "boxer": 6,
  "bull mastiff": 6,
  "Tibetan mastiff": 6,
  "French bulldog": 6,
  "Great Dane": 6,
  "Saint Bernard": 6,
  "Eskimo dog": 6,
  "malamute": 6,
  "Siberian husky": 6,
  "dalmatian": 6,
  "affenpinscher": 6,
  "basenji": 6,
  "pug": 6,
  "Leonberg": 6,
  "Newfoundland": 6,
  "Great Pyrenees": 6,
  "Samoyed": 6,
  "Pomeranian": 6,
  "chow": 6,
  "keeshond": 6,
  "Brabancon griffon": 6,
  "Pembroke": 6,
  "Cardigan": 6,
  "toy poodle": 6,
  "miniature poodle": 6,
  "standard poodle": 6,
  "Mexican hairless": 6,
  "timber wolf": 6,
  "white wolf": 6,
  "red wolf": 6,
  "coyote": 6,
  "dingo": 6,
  "dhole": 6,
  "African hunting dog": 6,
  "hyena": 6,
  "red fox": 6,
  "kit fox": 6,
  "Arctic fox": 6,
  "grey fox": 6,
  "tabby": 6,
  "tiger cat": 6,
  "Persian cat": 6,
  "Siamese cat": 6,
  "Egyptian cat": 6,
  "cougar": 6,
  "lynx": 6,
  "leopard": 6,
  "snow leopard": 6,
  "jaguar": 6,
  "lion": 6,
  "tiger": 6,
  "cheetah": 6,
  "brown bear": 6,
  "American black bear": 6,
  "ice bear": 6,
  "sloth bear": 6,
  "mongoose": 6,
  "meerkat": 6,
  "tiger beetle": 6,
  "ladybug": 6,
  "ground beetle": 6,
  "long-horned beetle": 6,
  "leaf beetle": 6,
  "dung beetle": 6,
  "rhinoceros beetle": 6,
  "weevil": 6,
  "fly": 6,
  "bee": 6,
  "ant": 6,
  "grasshopper": 6,
  "cricket": 6,
  "walking stick": 6,
  "cockroach": 6,
  "mantis": 6,
  "cicada": 6,
  "leafhopper": 6,
  "lacewing": 6,
  "dragonfly": 6,
  "damselfly": 6,
  "admiral": 6,
  "ringlet": 6,
  "monarch": 6,
  "cabbage butterfly": 6,
  "sulphur butterfly": 6,
  "lycaenid": 6,
  "starfish": 6,
  "sea urchin": 6,
  "sea cucumber": 6,
  "wood rabbit": 6,
  "hare": 6,
  "Angora": 6,
  "hamster": 6,
  "porcupine": 6,
  "fox squirrel": 6,
  "marmot": 6,
  "beaver": 6,
  "guinea pig": 6,
  "sorrel": 6,
  "zebra": 6,
  "hog": 6,
  "wild boar": 6,
  "warthog": 6,
  "hippopotamus": 6,
  "ox": 6,
  "water buffalo": 6,
  "bison": 6,
  "ram": 6,
  "bighorn": 6,
  "ibex": 6,
  "hartebeest": 6,
  "impala": 6,
  "gazelle": 6,
  "Arabian camel": 6,
  "llama": 6,
  "weasel": 6,
  "mink": 6,
  "polecat": 6,
  "black-footed ferret": 6,
  "otter": 6,
  "skunk": 6,
  "badger": 6,
  "armadillo": 6,
  "three-toed sloth": 6,
  "orangutan": 6,
  "gorilla": 6,
  "chimpanzee": 6,
  "gibbon": 6,
  "siamang": 6,
  "guenon": 6,
  "patas": 6,
  "baboon": 6,
  "macaque": 6,
  "langur": 6,
  "colobus": 6,
  "proboscis monkey": 6,
  "marmoset": 6,
  "capuchin": 6,
  "howler monkey": 6,
  "titi": 6,
  "spider monkey": 6,
  "squirrel monkey": 6,
  "Madagascar cat": 6,
  "indri": 6,
  "Indian elephant": 6,
  "African elephant": 6,
  "lesser panda": 6,
  "giant panda": 6,
  "barracouta": 6,
  "eel": 6,
  "coho": 6,
  "rock beauty": 6,
  "anemone fish": 6,
  "sturgeon": 6,
  "gar": 6,
  "lionfish": 6,
  "puffer": 6,
  "abacus": 2,
  "abaya": 1,
  "academic gown": 1,
  "accordion": 5,
  "acoustic guitar": 2,
  "aircraft carrier": 5,
  "airliner": 5,
  "airship": 5,
  "altar": 9,
  "ambulance": 5,
  "amphibian": 6,
  "analog clock": 8,
  "apiary": 6,
  "apron": 1,
  "ashcan": 5,
  "assault rifle": 5,
  "backpack": 1,
  "bakery": 6,
  "balance beam": 5,
  "balloon": 8,
  "ballpoint": 8,
  "Band Aid": 4,
  "banjo": 2,
  "bannister": 9,
  "barbell": 5,
  "barber chair": 8,
  "barbershop": 9,
  "barn": 6,
  "barometer": 2,
  "barrel": 5,
  "barrow": 6,
  "baseball": 9,
  "basketball": 9,
  "bassinet": 5,
  "bassoon": 5,
  "bathing cap": 8,
  "bath towel": 1,
  "bathtub": 8,
  "beach wagon": 8,
  "beacon": 9,
  "beaker": 8,
  "bearskin": 1,
  "beer bottle": 3,
  "beer glass": 3,
  "bell cote": 5,
  "bib": 1,
  "bicycle-built-for-two": 5,
  "bikini": 1,
  "binder": 8,
  "binoculars": 8,
  "birdhouse": 6,
  "boathouse": 6,
  "bobsled": 5,
  "bolo tie": 1,
  "bonnet": 1,
  "bookcase": 8,
  "bookshop": 9,
  "bottlecap": 8,
  "bow": 5,
  "bow tie": 1,
  "brass": 5,
  "brassiere": 1,
  "breakwater": 6,
  "breastplate": 5,
  "broom": 8,
  "bucket": 8,
  "buckle": 5,
  "bulletproof vest": 5,
  "bullet train": 5,
  "butcher shop": 9,
  "cab": 5,
  "caldron": 5,
  "candle": 6,
  "cannon": 5,
  "canoe": 6,
  "can opener": 5,
  "cardigan": 1,
  "car mirror": 3,
  "carousel": 5,
  "carpenter's kit": 5,
  "carton": 7,
  "car wheel": 8,
  "cash machine": 5,
  "cassette": 8,
  "cassette player": 8,
  "castle": 6,
  "catamaran": 5,
  "CD player": 8,
  "cello": 2,
  "cellular telephone": 2,
  "chain": 5,
  "chainlink fence": 5,
  "chain mail": 5,
  "chain saw": 5,
  "chest": 6,
  "chiffonier": 6,
  "chime": 5,
  "china cabinet": 6,
  "Christmas stocking": 1,
  "church": 6,
  "cinema": 9,
  "cleaver": 5,
  "cliff dwelling": 6,
  "cloak": 1,
  "clog": 8,
  "cocktail shaker": 4,
  "coffee mug": 8,
  "coffeepot": 2,
  "coil": 5,
  "combination lock": 5,
  "computer keyboard": 2,
  "confectionery": 9,
  "container ship": 4,
  "convertible": 9,
  "corkscrew": 5,
  "cornet": 5,
  "cowboy boot": 1,
  "cowboy hat": 1,
  "cradle": 6,
  "crane": 5,
  "crash helmet": 8,
  "crate": 6,
  "crib": 6,
  "Crock Pot": 2,
  "croquet ball": 8,
  "crutch": 5,
  "cuirass": 5,
  "dam": 9,
  "desk": 6,
  "desktop computer": 2,
  "dial telephone": 2,
  "diaper": 1,
  "digital clock": 2,
  "digital watch": 8,
  "dining table": 6,
  "dishrag": 1,
  "dishwasher": 2,
  "disk brake": 5,
  "dock": 6,
  "dogsled": 9,
  "dome": 9,
  "doormat": 1,
  "drilling platform": 5,
  "drum": 5,
  "drumstick": 6,
  "dumbbell": 5,
  "Dutch oven": 5,
  "electric fan": 2,
  "electric guitar": 2,
  "electric locomotive": 5,
  "entertainment center": 6,
  "envelope": 7,
  "espresso maker": 2,
  "face powder": 4,
  "feather boa": 1,
  "file": 7,
  "fireboat": 5,
  "fire engine": 5,
  "fire screen": 5,
  "flagpole": 5,
  "flute": 6,
  "folding chair": 5,
  "football helmet": 5,
  "forklift": 5,
  "fountain": 6,
  "fountain pen": 8,
  "four-poster": 6,
  "freight car": 5,
  "French horn": 5,
  "frying pan": 5,
  "fur coat": 1,
  "garbage truck": 5,
  "gasmask": 4,
  "gas pump": 5,
  "goblet": 3,
  "go-kart": 5,
  "golf ball": 6,
  "golfcart": 5,
  "gondola": 6,
  "gong": 5,
  "gown": 1,
  "grand piano": 6,
  "greenhouse": 6,
  "grille": 5,
  "grocery store": 9,
  "guillotine": 6,
  "hair slide": 6,
  "hair spray": 4,
  "half track": 5,
  "hammer": 5,
  "hamper": 8,
  "hand blower": 2,
  "hand-held computer": 2,
  "handkerchief": 1,
  "hard disc": 2,
  "harmonica": 5,
  "harp": 6,
  "harvester": 5,
  "hatchet": 5,
  "holster": 1,
  "home theater": 2,
  "honeycomb": 6,
  "hook": 5,
  "hoopskirt": 1,
  "horizontal bar": 5,
  "horse cart": 6,
  "hourglass": 3,
  "iPod": 2,
  "iron": 2,
  "jack-o'-lantern": 6,
  "jean": 1,
  "jeep": 5,
  "jersey": 1,
  "jigsaw puzzle": 7,
  "jinrikisha": 6,
  "joystick": 2,
  "kimono": 1,
  "knee pad": 1,
  "knot": 1,
  "lab coat": 1,
  "ladle": 5,
  "lampshade": 5,
  "laptop": 2,
  "lawn mower": 2,
  "lens cap": 8,
  "letter opener": 5,
  "library": 9,
  "lifeboat": 8,
  "lighter": 5,
  "limousine": 5,
  "liner": 4,
  "lipstick": 4,
  "Loafer": 1,
  "lotion": 8,
  "loudspeaker": 2,
  "loupe": 3,
  "lumbermill": 6,
  "magnetic compass": 5,
  "mailbag": 1,
  "mailbox": 5,
  "maillot": 1,
  "maillot": 1,
  "manhole cover": 5,
  "maraca": 6,
  "marimba": 6,
  "mask": 4,
  "matchstick": 6,
  "maypole": 9,
  "maze": 9,
  "measuring cup": 3,
  "medicine chest": 4,
  "megalith": 9,
  "microphone": 2,
  "microwave": 2,
  "military uniform": 1,
  "milk can": 5,
  "minibus": 5,
  "miniskirt": 1,
  "minivan": 5,
  "missile": 5,
  "mitten": 1,
  "mixing bowl": 5,
  "mobile home": 2,
  "Model T": 5,
  "modem": 2,
  "monastery": 9,
  "monitor": 2,
  "moped": 5,
  "mortar": 6,
  "mortarboard": 1,
  "mosque": 9,
  "mosquito net": 8,
  "motor scooter": 5,
  "mountain bike": 5,
  "mountain tent": 8,
  "mouse": 2,
  "mousetrap": 5,
  "moving van": 5,
  "muzzle": 8,
  "nail": 6,
  "neck brace": 1,
  "necklace": 5,
  "nipple": 8,
  "notebook": 7,
  "obelisk": 9,
  "oboe": 5,
  "ocarina": 8,
  "odometer": 8,
  "oil filter": 5,
  "organ": 6,
  "oscilloscope": 5,
  "overskirt": 1,
  "oxcart": 6,
  "oxygen mask": 4,
  "packet": 8,
  "paddle": 8,
  "paddlewheel": 8,
  "padlock": 5,
  "paintbrush": 8,
  "pajama": 1,
  "palace": 6,
  "panpipe": 6,
  "paper towel": 7,
  "parachute": 8,
  "parallel bars": 5,
  "park bench": 6,
  "parking meter": 2,
  "passenger car": 5,
  "patio": 6,
  "pay-phone": 2,
  "pedestal": 8,
  "pencil box": 8,
  "pencil sharpener": 8,
  "perfume": 4,
  "Petri dish": 3,
  "photocopier": 2,
  "pick": 5,
  "pickelhaube": 5,
  "picket fence": 6,
  "pickup": 5,
  "pier": 6,
  "piggy bank": 8,
  "pill bottle": 4,
  "pillow": 1,
  "ping-pong ball": 8,
  "pinwheel": 7,
  "pirate": 1,
  "pitcher": 3,
  "plane": 5,
  "planetarium": 6,
  "plastic bag": 8,
  "plate rack": 5,
  "plow": 5,
  "plunger": 8,
  "Polaroid camera": 2,
  "pole": 5,
  "police van": 5,
  "poncho": 1,
  "pool table": 6,
  "pop bottle": 3,
  "pot": 6,
  "potter's wheel": 6,
  "power drill": 5,
  "prayer rug": 1,
  "printer": 2,
  "prison": 5,
  "projectile": 9,
  "projector": 2,
  "puck": 2,
  "punching bag": 1,
  "purse": 1,
  "quill": 6,
  "quilt": 1,
  "racer": 1,
  "racket": 8,
  "radiator": 2,
  "radio": 2,
  "radio telescope": 2,
  "rain barrel": 9,
  "recreational vehicle": 5,
  "reel": 9,
  "reflex camera": 2,
  "refrigerator": 2,
  "remote control": 2,
  "restaurant": 6,
  "revolver": 5,
  "rifle": 5,
  "rocking chair": 6,
  "rotisserie": 6,
  "rubber eraser": 6,
  "rugby ball": 1,
  "rule": 8,
  "running shoe": 1,
  "safe": 5,
  "safety pin": 5,
  "saltshaker": 8,
  "sandal": 1,
  "sarong": 1,
  "sax": 9,
  "scabbard": 5,
  "scale": 8,
  "school bus": 5,
  "schooner": 6,
  "scoreboard": 2,
  "screen": 2,
  "screw": 5,
  "screwdriver": 5,
  "seat belt": 8,
  "sewing machine": 5,
  "shield": 5,
  "shoe shop": 9,
  "shoji": 3,
  "shopping basket": 8,
  "shopping cart": 5,
  "shovel": 5,
  "shower cap": 8,
  "shower curtain": 8,
  "ski": 8,
  "ski mask": 1,
  "sleeping bag": 8,
  "slide rule": 8,
  "sliding door": 6,
  "slot": 5,
  "snorkel": 8,
  "snowmobile": 2,
  "snowplow": 5,
  "soap dispenser": 2,
  "soccer ball": 8,
  "sock": 1,
  "solar dish": 2,
  "sombrero": 1,
  "soup bowl": 8,
  "space bar": 2,
  "space heater": 2,
  "space shuttle": 5,
  "spatula": 5,
  "speedboat": 8,
  "spider web": 6,
  "spindle": 5,
  "sports car": 5,
  "spotlight": 2,
  "stage": 9,
  "steam locomotive": 5,
  "steel arch bridge": 5,
  "steel drum": 5,
  "stethoscope": 4,
  "stole": 1,
  "stone wall": 6,
  "stopwatch": 2,
  "stove": 5,
  "strainer": 5,
  "streetcar": 5,
  "stretcher": 8,
  "studio couch": 1,
  "stupa": 6,
  "submarine": 5,
  "suit": 1,
  "sundial": 2,
  "sunglass": 8,
  "sunglasses": 8,
  "sunscreen": 4,
  "suspension bridge": 5,
  "swab": 4,
  "sweatshirt": 1,
  "swimming trunks": 1,
  "swing": 5,
  "switch": 2,
  "syringe": 4,
  "table lamp": 2,
  "tank": 5,
  "tape player": 2,
  "teapot": 3,
  "teddy": 1,
  "television": 2,
  "tennis ball": 1,
  "thatch": 6,
  "theater curtain": 9,
  "thimble": 5,
  "thresher": 5,
  "throne": 5,
  "tile roof": 6,
  "toaster": 1,
  "tobacco shop": 9,
  "toilet seat": 8,
  "torch": 2,
  "totem pole": 6,
  "tow truck": 5,
  "toyshop": 8,
  "tractor": 5,
  "trailer truck": 5,
  "tray": 8,
  "trench coat": 1,
  "tricycle": 5,
  "trimaran": 8,
  "tripod": 8,
  "triumphal arch": 6,
  "trolleybus": 5,
  "trombone": 5,
  "tub": 8,
  "turnstile": 5,
  "typewriter keyboard": 2,
  "umbrella": 8,
  "unicycle": 5,
  "upright": 9,
  "vacuum": 9,
  "vase": 3,
  "vault": 5,
  "velvet": 1,
  "vending machine": 2,
  "vestment": 1,
  "viaduct": 6,
  "violin": 6,
  "volleyball": 8,
  "waffle iron": 5,
  "wall clock": 6,
  "wallet": 1,
  "wardrobe": 6,
  "warplane": 5,
  "washbasin": 3,
  "washer": 5,
  "water bottle": 8,
  "water jug": 8,
  "water tower": 5,
  "whiskey jug": 3,
  "whistle": 8,
  "wig": 5,
  "window screen": 3,
  "window shade": 1,
  "Windsor tie": 1,
  "wine bottle": 3,
  "wing": 8,
  "wok": 5,
  "wooden spoon": 6,
  "wool": 6,
  "worm fence": 6,
  "wreck": 5,
  "yawl": 5,
  "yurt": 6,
  "web site": 2,
  "comic book": 7,
  "crossword puzzle": 7,
  "street sign": 5,
  "traffic light": 2,
  "book jacket": 7,
  "menu": 7,
  "plate": 3,
  "guacamole": 6,
  "consomme": 6,
  "hot pot": 5,
  "trifle": 6,
  "ice cream": 6,
  "ice lolly": 6,
  "French loaf": 6,
  "bagel": 6,
  "pretzel": 6,
  "cheeseburger": 6,
  "hotdog": 6,
  "mashed potato": 6,
  "head cabbage": 6,
  "broccoli": 6,
  "cauliflower": 6,
  "zucchini": 6,
  "spaghetti squash": 6,
  "acorn squash": 6,
  "butternut squash": 6,
  "cucumber": 6,
  "artichoke": 6,
  "bell pepper": 6,
  "cardoon": 6,
  "mushroom": 6,
  "Granny Smith": 6,
  "strawberry": 6,
  "orange": 6,
  "lemon": 6,
  "fig": 6,
  "pineapple": 6,
  "banana": 6,
  "jackfruit": 6,
  "custard apple": 6,
  "pomegranate": 6,
  "hay": 6,
  "carbonara": 6,
  "chocolate sauce": 6,
  "dough": 6,
  "meat loaf": 6,
  "pizza": 6,
  "potpie": 6,
  "burrito": 6,
  "red wine": 3,
  "espresso": 3,
  "cup": 3,
  "eggnog": 6,
  "alp": 9,
  "bubble": 3,
  "cliff": 6,
  "coral reef": 6,
  "geyser": 5,
  "lakeside": 6,
  "promontory": 6,
  "sandbar": 6,
  "seashore": 6,
  "valley": 6,
  "volcano": 6,
  "ballplayer": 9,
  "groom": 2,
  "scuba diver": 9,
  "rapeseed": 6,
  "daisy": 6,
  "yellow lady's slipper": 6,
  "corn": 6,
  "acorn": 6,
  "hip": 6,
  "buckeye": 6,
  "coral fungus": 6,
  "agaric": 6,
  "gyromitra": 6,
  "stinkhorn": 6,
  "earthstar": 6,
  "hen-of-the-woods": 6,
  "bolete": 6,
  "ear": 6,
  "toilet tissue": 7,
};
